name: SmartTech Solutions
title: IT Support & AI for Small Business
description: We help small businesses with reliable IT support and bring them into the AI age.
author: Carter
email: smartmoneyai.org@pm.me
permalink: /:title/
future: true
defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: "_posts"
    values:
      layout: post